"""Jobs routes for DataMind-King."""

from __future__ import annotations

from datetime import datetime, timezone
from http import HTTPStatus

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.db import get_db
from app.models.job import Job
from app.models.user import User

router = APIRouter(prefix="", tags=["jobs"])


async def require_user(db: AsyncSession = Depends(get_db), user=None) -> User:
    """Placeholder dependency for user auth."""
    return user  # type: ignore[return-value]


@router.get("", tags=["jobs-list"])
async def list_jobs(
    db: AsyncSession = Depends(get_db),
    user: User | None = Depends(require_user),
    limit: int = 50,
    offset: int = 0,
) -> dict:
    """List jobs for the current organization."""
    stmt = (
        select(Job)
        .where(Job.org_id == user.org_id)
        .order_by(Job.created_at.desc())
        .offset(offset)
        .limit(limit)
    )
    result = await db.execute(stmt)
    jobs = result.scalars().all()
    return {"items": [j.__dict__ for j in jobs], "total": len(jobs)}


@router.post("", status_code=HTTPStatus.CREATED, tags=["jobs-create"])
async def create_job(
    body: dict,
    db: AsyncSession = Depends(get_db),
    user: User | None = Depends(require_user),
) -> dict:
    """Create a new analysis job."""
    job = Job(
        id="",  # UUID generated by caller
        org_id=user.org_id,
        dataset_id=body.get("dataset_id"),
        agent_name=body["agent_name"],
        prompt=body.get("prompt", ""),
        status="pending",
    )
    db.add(job)
    await db.commit()
    await db.refresh(job)
    return job.__dict__


@router.get("/{job_id}", tags=["jobs-get"])
async def get_job(
    job_id: str,
    db: AsyncSession = Depends(get_db),
    user: User | None = Depends(require_user),
) -> dict:
    """Get a single job, enforcing tenant isolation."""
    job = (await db.execute(
        select(Job).where(
            (Job.id == job_id) & (Job.org_id == user.org_id)
        )
    )).scalar_one_or_none()
    if job is None:
        raise HTTPException(status_code=HTTPStatus.NOT_FOUND, detail="Job not found")
    return job.__dict__


@router.delete("/{job_id}", status_code=HTTPStatus.NO_CONTENT, tags=["jobs-delete"])
async def delete_job(
    job_id: str,
    db: AsyncSession = Depends(get_db),
    user: User | None = Depends(require_user),
) -> None:
    """Delete a job, enforcing tenant isolation."""
    job = (await db.execute(
        select(Job).where(
            (Job.id == job_id) & (Job.org_id == user.org_id)
        )
    )).scalar_one_or_none()
    if job is None:
        raise HTTPException(status_code=HTTPStatus.NOT_FOUND, detail="Job not found")
    await db.delete(job)
    await db.commit()
